# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pon.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tpon.proto\x12\x03pon\"$\n\x03Onu\x12\x0e\n\x06portid\x18\x01 \x01(\x05\x12\r\n\x05onuid\x18\x02 \x01(\x05\"\x1b\n\x08PonReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\x88\x01\n\nPonService\x12(\n\x0bOnuActivate\x12\x08.pon.Onu\x1a\r.pon.PonReply\"\x00\x12\'\n\rOnuDeactivate\x12\x08.pon.Onu\x1a\n.pon.Empty\"\x00\x12\'\n\rOnuIndication\x12\x08.pon.Onu\x1a\x08.pon.Onu\"\x00\x30\x01\x62\x06proto3')



_ONU = DESCRIPTOR.message_types_by_name['Onu']
_PONREPLY = DESCRIPTOR.message_types_by_name['PonReply']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
Onu = _reflection.GeneratedProtocolMessageType('Onu', (_message.Message,), {
  'DESCRIPTOR' : _ONU,
  '__module__' : 'pon_pb2'
  # @@protoc_insertion_point(class_scope:pon.Onu)
  })
_sym_db.RegisterMessage(Onu)

PonReply = _reflection.GeneratedProtocolMessageType('PonReply', (_message.Message,), {
  'DESCRIPTOR' : _PONREPLY,
  '__module__' : 'pon_pb2'
  # @@protoc_insertion_point(class_scope:pon.PonReply)
  })
_sym_db.RegisterMessage(PonReply)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'pon_pb2'
  # @@protoc_insertion_point(class_scope:pon.Empty)
  })
_sym_db.RegisterMessage(Empty)

_PONSERVICE = DESCRIPTOR.services_by_name['PonService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ONU._serialized_start=18
  _ONU._serialized_end=54
  _PONREPLY._serialized_start=56
  _PONREPLY._serialized_end=83
  _EMPTY._serialized_start=85
  _EMPTY._serialized_end=92
  _PONSERVICE._serialized_start=95
  _PONSERVICE._serialized_end=231
# @@protoc_insertion_point(module_scope)
