# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pon_pb2 as pon__pb2


class PonServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnuActivate = channel.unary_unary(
                '/pon.PonService/OnuActivate',
                request_serializer=pon__pb2.Onu.SerializeToString,
                response_deserializer=pon__pb2.PonReply.FromString,
                )
        self.OnuDeactivate = channel.unary_unary(
                '/pon.PonService/OnuDeactivate',
                request_serializer=pon__pb2.Onu.SerializeToString,
                response_deserializer=pon__pb2.Empty.FromString,
                )
        self.OnuIndication = channel.unary_stream(
                '/pon.PonService/OnuIndication',
                request_serializer=pon__pb2.Onu.SerializeToString,
                response_deserializer=pon__pb2.Onu.FromString,
                )


class PonServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OnuActivate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnuDeactivate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnuIndication(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PonServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnuActivate': grpc.unary_unary_rpc_method_handler(
                    servicer.OnuActivate,
                    request_deserializer=pon__pb2.Onu.FromString,
                    response_serializer=pon__pb2.PonReply.SerializeToString,
            ),
            'OnuDeactivate': grpc.unary_unary_rpc_method_handler(
                    servicer.OnuDeactivate,
                    request_deserializer=pon__pb2.Onu.FromString,
                    response_serializer=pon__pb2.Empty.SerializeToString,
            ),
            'OnuIndication': grpc.unary_stream_rpc_method_handler(
                    servicer.OnuIndication,
                    request_deserializer=pon__pb2.Onu.FromString,
                    response_serializer=pon__pb2.Onu.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pon.PonService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PonService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OnuActivate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pon.PonService/OnuActivate',
            pon__pb2.Onu.SerializeToString,
            pon__pb2.PonReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OnuDeactivate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pon.PonService/OnuDeactivate',
            pon__pb2.Onu.SerializeToString,
            pon__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OnuIndication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/pon.PonService/OnuIndication',
            pon__pb2.Onu.SerializeToString,
            pon__pb2.Onu.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
